# Generated by Django 5.1.3 on 2024-12-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_image_alter_item_place_alter_item_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
